/* 
This program is a task submission for the Java Programming Internship at Oasis InfoByte
It's a Number-Guess game where the user has to guess the random number generated by the computer within 10 tries. 
It's a simple terminal interface program with basic user interaction facilities on the CLI
*/

// Imports the necessary classes from the built-in Util library for the game
import java.util.Scanner;
import java.util.Random; 


public class Game {
    public static void main (String[] args) {
        Scanner sc = new Scanner(System.in); 
        Random r = new Random(); // Creating r variable for random object

        int num = r.nextInt(100) + 1; // A random number is picked from 1-100
        int attempts = 0, maxAttempts = 10, guess = 0, choice = 0; // Declaring & initializing other necessary variables

        System.out.println("Welcome to the Guess-The-Number Game!");
        while (choice != 3) { // Loop to keep the program running until the user chooses to exit manually
          //Printing out the lines for the main menu of the game
            System.out.println("===================================================="); 
            System.out.println("\nHow would you like to proceed? "); 
            System.out.println("1. Instructions \n2. Play the Game \n3. Exit"); 
            System.out.println("Enter your choice: "); 
            choice = sc.nextInt(); 
            System.out.println(); 
          // Checking the which block of statements to run becased on user's choice
            if (choice == 1) {  // If the user chose to view the rules of the game
                System.out.println("===============================================");
                System.out.println("How to Play? "); 
                System.out.println("1. You get 10 chances to guess the number."); 
                System.out.println("2. Each time you'll be told whether you guesses low or high from the actual number."); 
                System.out.println("3. If you manage to guess within 10 chances then you win the game. Otherwise you lose."); 
                System.out.println("==============================================="); 
            }
            else if (choice == 2) {  // If the user chose to play the game
                System.out.println("Hello, Player! Let's start the game--"); 
                while (attempts < maxAttempts) {  // Loop to iterate until the user either runs out of maximum attempts or managed to guess correctly 
                    System.out.println("Make your Guess " + attempts + " : "); 
                    guess = sc.nextInt(); 
                    if (guess < num) {
                        System.out.println("Too low! Try again~"); 
                        System.out.println("Number of attempts left: " + (maxAttempts - attempts)); 
                    }
                    else if (guess > num) {
                        System.out.println("Too high! Try again~"); 
                        System.out.println("Number of attempts left: " + (maxAttempts - attempts)); 
                    }
                    else {
                        System.out.println("Correct! Your guess was just right");
                        System.out.println("Taking you back to main menu.......");  
                        break;
                    }
                    attempts++; // Updates the number of attempts by the user for each loop's iteraction
                }
                if (attempts == maxAttempts) {  // Checks if the user managed to use up all the attempts given for the guess
                    System.out.println("You've used all your guess chances!");
                    System.out.println("You failed to guess the number " + num); 
                }
            }
            else if (choice == 3) {  // If the user chooses to exit the game
                System.out.println("Goodbye Player! Exiting the game....."); 
                break; 
            }
            else   // Else statement for any other inputs the user enters
                System.out.println("Invalid choice! Choose an option from 1-3....."); 
        }
    }
}
